version: '3.7'

services:
  postgres:
    image: postgres:latest
    volumes:
      - ./pg_data:/var/lib/postgresql
    networks:
      - default
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db

  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres